version: '3.4'

services:
  query:
    image: query
    build:
      context: query
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4002:4002
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
