apiVersion: v1
kind: Pod
metadata:
  name: query
  labels:
    app: query
    rel: stable
spec:
  containers:
    - name: query
      image: furelteguimene/query:latest
      ports:
        - containerPort: 80
      resources: {}