apiVersion: v1
kind: Pod
metadata:
  name: moderation
  labels:
    app: moderation
    rel: stable
spec:
  containers:
    - name: moderation
      image: furelteguimene/moderation:latest
      ports:
        - containerPort: 80
      resources: {}