apiVersion: v1
kind: Pod
metadata:
  name: posts
  labels:
    app: posts
    rel: stable
spec:
  containers:
    - name: posts
      image: furelteguimene/posts:latest
      ports:
        - containerPort: 80
      resources: {}