apiVersion: v1
kind: Pod
metadata:
  name: posts-pod2
  labels:
    app: tp-blog
    rel: stable
spec:
  containers:
    - name: posts-container
      image: posts
      ports:
        - containerPort: 4000
      resources: {}